// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcD_gA1HRn6Hqc1lp3t5QgSyBkMsbKjOk',
    appId: '1:222009577197:web:14c4a796c6f3d11c7346e4',
    messagingSenderId: '222009577197',
    projectId: 'studyapp-98a41',
    authDomain: 'studyapp-98a41.firebaseapp.com',
    storageBucket: 'studyapp-98a41.appspot.com',
    measurementId: 'G-8ELMGK0SPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RfvDGYgYdbz-miJDmACWdvvn3qDxYrQ',
    appId: '1:222009577197:android:0c76749ce18b293a7346e4',
    messagingSenderId: '222009577197',
    projectId: 'studyapp-98a41',
    storageBucket: 'studyapp-98a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXc_NLy0A68von4k8tPOVS-e61w5dDRQ',
    appId: '1:222009577197:ios:453e716ec94f8c797346e4',
    messagingSenderId: '222009577197',
    projectId: 'studyapp-98a41',
    storageBucket: 'studyapp-98a41.appspot.com',
    iosClientId: '222009577197-nd5k63m6t24fnameri2dbeepeok87gpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVXc_NLy0A68von4k8tPOVS-e61w5dDRQ',
    appId: '1:222009577197:ios:453e716ec94f8c797346e4',
    messagingSenderId: '222009577197',
    projectId: 'studyapp-98a41',
    storageBucket: 'studyapp-98a41.appspot.com',
    iosClientId: '222009577197-nd5k63m6t24fnameri2dbeepeok87gpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
